In [1]:
import pandas as pd
import sys
import os
sys.path.insert(0, '/home/hugo/gitlab.pavlovia/online_test/code')
from my_analysis.data_loader import load_and_aggregate
from my_analysis.utils import calculate_dice
from sklearn.metrics import cohen_kappa_score
import numpy as np
import datetime
import plotly.express as px

In [2]:
data_path = os.path.join('/home/hugo/gitlab.pavlovia/online_test', 'data')
output_dir = os.path.join('/home/hugo/gitlab.pavlovia/online_test', 'outputdata')
print(f"Loading files ...")
df = load_and_aggregate(data_path, cutoff=datetime.datetime(2026, 3, 25), save_data=True)

Loading files ...
Processing file /home/hugo/gitlab.pavlovia/online_test/data/879453_online_test_2026-04-16_15h28.06.260.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/864767_online_test_2026-04-16_15h15.08.024.csv
File /home/hugo/gitlab.pavlovia/online_test/data/544729_online_test_2026-03-19_11h46.10.203.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/951008_online_test_2026-04-16_15h39.23.879.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/834677_online_test_2026-04-16_15h15.08.331.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/273984_online_test_2026-04-09_20h47.09.488.csv
File /home/hugo/gitlab.pavlovia/online_test/data/252796_online_test_2026-02-08_16h57.24.888.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/692878_online_test_2026-03-26_21h22.57.690.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/917300_online_test_2026-04-16_10h15.30.443.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/695036_online_test_2026-04-16_15h15.41.917.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/642560_online_test_2026-03-26_17h22.38.321.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/853983_online_test_2026-04-16_14h15.52.520.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/130790_online_test_2026-04-16_20h17.52.818.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/993106_online_test_2026-04-09_15h37.34.921.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/563725_online_test_2026-04-16_15h15.37.947.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/075955_online_test_2026-03-26_12h35.14.608.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/409227_online_test_2026-04-16_20h14.52.483.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/018000_online_test_2026-04-16_22h16.01.478.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/431257_online_test_2026-04-16_15h19.06.457.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/363261_online_test_2026-04-16_15h15.21.781.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/271446_online_test_2026-04-16_14h15.01.780.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/088902_online_test_2026-04-16_15h22.59.079.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/480816_online_test_2026-04-16_15h39.37.796.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/198216_online_test_2026-04-16_15h21.14.391.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/156113_online_test_2026-04-16_14h14.47.089.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/415727_online_test_2026-04-16_16h37.19.890.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/801257_online_test_2026-04-16_14h15.16.646.csv
File /home/hugo/gitlab.pavlovia/online_test/data/488798_online_test_2026-02-12_10h58.22.308.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/268535_online_test_2026-04-16_15h15.51.124.csv
File /home/hugo/gitlab.pavlovia/online_test/data/891930_online_test_2025-10-09_13h51.36.072.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/104198_online_test_2026-04-16_15h15.16.741.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/594625_online_test_2026-03-25_14h21.31.742.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/078420_online_test_2026-04-16_16h15.23.799.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/031426_online_test_2026-04-02_18h06.15.444.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/352071_online_test_2026-04-16_15h17.08.749.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/238512_online_test_2026-04-16_15h18.06.076.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/947821_online_test_2026-04-16_15h20.28.847.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/023635_online_test_2026-03-25_14h23.53.442.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/124671_online_test_2026-04-16_14h15.08.822.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/273616_online_test_2026-03-25_21h45.52.046.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/050267_online_test_2026-04-16_18h52.15.697.csv
File /home/hugo/gitlab.pavlovia/online_test/data/115434_online_test_2026-02-08_17h12.05.403.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/416380_online_test_2026-04-02_19h18.39.447.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/068457_online_test_2026-04-16_09h16.50.184.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/677644_online_test_2026-03-26_12h25.20.712.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/323755_online_test_2026-04-16_15h14.50.347.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/074234_online_test_2026-04-16_14h15.07.319.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/639179_online_test_2026-04-16_14h15.10.030.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/055374_online_test_2026-04-16_15h22.48.110.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/575951_online_test_2026-04-16_15h23.15.364.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/110463_online_test_2026-04-16_15h16.58.243.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/827375_online_test_2026-04-16_10h29.09.028.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/113329_online_test_2026-04-16_15h27.13.382.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/872112_online_test_2026-04-16_15h14.44.005.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/460079_online_test_2026-04-16_15h17.35.930.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/847476_online_test_2026-04-16_15h18.19.364.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/676237_online_test_2026-03-25_15h22.37.772.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/969185_online_test_2026-04-16_15h20.35.724.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/155254_online_test_2026-04-16_10h17.22.052.csv
File /home/hugo/gitlab.pavlovia/online_test/data/883028_online_test_2026-02-06_10h45.10.737.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/058716_online_test_2026-04-16_15h39.38.801.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/400235_online_test_2026-04-16_14h15.44.193.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/716173_online_test_2026-04-16_18h48.38.175.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/556456_online_test_2026-04-16_15h20.45.146.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/973002_online_test_2026-04-02_19h06.20.036.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/744976_online_test_2026-03-26_12h52.57.431.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/613568_online_test_2026-04-16_14h25.06.041.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/991701_online_test_2026-04-16_09h20.12.645.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/831257_online_test_2026-04-16_15h21.53.100.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/280984_online_test_2026-04-16_15h15.35.836.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/835943_online_test_2026-04-16_14h20.09.264.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/435070_online_test_2026-03-26_12h41.49.155.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/720524_online_test_2026-04-16_15h28.37.880.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/565503_online_test_2026-04-16_16h19.08.706.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/499523_online_test_2026-03-26_17h46.21.018.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/736928_online_test_2026-04-16_15h15.22.527.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/591185_online_test_2026-04-16_09h15.16.894.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/616004_online_test_2026-04-16_15h18.35.879.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/768196_online_test_2026-04-16_15h21.00.712.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/002502_online_test_2026-03-26_10h32.49.897.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/031856_online_test_2026-03-26_13h24.23.998.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/822101_online_test_2026-04-16_15h34.27.723.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/948679_online_test_2026-03-26_10h25.51.193.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/763741_online_test_2026-04-16_15h19.49.415.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/441593_online_test_2026-03-30_10h37.13.379.csv
File /home/hugo/gitlab.pavlovia/online_test/data/989304_online_test_2026-02-22_16h09.44.620.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/480573_online_test_2026-03-26_18h27.08.419.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/644849_online_test_2026-04-16_16h16.43.878.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/600825_online_test_2026-04-16_14h22.13.733.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/091294_online_test_2026-04-09_12h34.38.070.csv
File /home/hugo/gitlab.pavlovia/online_test/data/170418_online_test_2026-02-08_17h42.14.774.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/037413_online_test_2026-04-16_14h16.50.617.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/313657_online_test_2026-04-16_15h15.20.003.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/296648_online_test_2026-04-16_15h16.12.979.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/695098_online_test_2026-04-16_21h15.13.572.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/088838_online_test_2026-04-16_15h15.30.208.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/258813_online_test_2026-04-16_17h14.51.629.csv
File /home/hugo/gitlab.pavlovia/online_test/data/717499_online_test_2026-02-12_10h57.18.204.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/339088_online_test_2026-04-09_13h35.45.697.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/033170_online_test_2026-04-16_14h39.04.223.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/530249_online_test_2026-03-26_17h29.06.449.csv
File /home/hugo/gitlab.pavlovia/online_test/data/585624_online_test_2025-09-15_14h45.52.710.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/653177_online_test_2026-04-16_15h16.07.159.csv
File /home/hugo/gitlab.pavlovia/online_test/data/192662_online_test_2026-02-12_11h18.33.046.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/441298_online_test_2026-04-16_15h22.51.066.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/962185_online_test_2026-04-16_09h14.59.028.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/969398_online_test_2026-04-16_15h15.11.825.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/912462_online_test_2026-04-16_15h15.27.911.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/294451_online_test_2026-04-16_15h18.05.539.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/115306_online_test_2026-04-16_15h15.22.462.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/389870_online_test_2026-03-26_10h22.56.069.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/863174_online_test_2026-04-16_16h15.07.377.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/593067_online_test_2026-04-16_15h19.05.012.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/454360_online_test_2026-04-16_15h17.10.031.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/639295_online_test_2026-04-16_16h15.27.375.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/803123_online_test_2026-04-16_22h16.04.949.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/290603_online_test_2026-04-16_22h15.28.684.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/937891_online_test_2026-04-16_15h15.45.723.csv
File /home/hugo/gitlab.pavlovia/online_test/data/557272_online_test_2026-02-11_16h14.26.702.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/235526_online_test_2026-04-16_15h15.25.537.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/878639_online_test_2026-04-16_15h25.48.833.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/397562_online_test_2026-04-16_14h14.52.891.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/010112_online_test_2026-04-16_15h15.57.099.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/001247_online_test_2026-04-16_10h15.47.449.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/011745_online_test_2026-04-16_15h15.19.018.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/706227_online_test_2026-04-16_09h15.16.708.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/034356_online_test_2026-04-16_15h38.38.016.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/046987_online_test_2026-04-16_14h29.29.564.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/697a4cfcf85e8d874a96481d_online_test_2026-03-25_14h21.28.563.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/597275_online_test_2026-04-16_09h18.50.772.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/531284_online_test_2026-04-16_14h16.44.835.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/922145_online_test_2026-04-16_16h14.58.071.csv
File /home/hugo/gitlab.pavlovia/online_test/data/418018_online_test_2026-03-19_11h45.47.671.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/244616_online_test_2026-04-16_15h16.15.614.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/713209_online_test_2026-03-26_23h42.41.478.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/954625_online_test_2026-04-16_10h14.58.549.csv
File /home/hugo/gitlab.pavlovia/online_test/data/648405_online_test_2025-09-16_11h56.52.469.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/305565_online_test_2026-04-09_20h35.37.789.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/502598_online_test_2026-03-26_16h41.00.209.csv
File /home/hugo/gitlab.pavlovia/online_test/data/836656_online_test_2026-02-08_17h33.11.138.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/396520_online_test_2026-04-16_16h15.25.701.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/111999_online_test_2026-04-16_15h15.27.283.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/845031_online_test_2026-03-26_16h25.37.172.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/676611_online_test_2026-03-26_14h21.40.789.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/446704_online_test_2026-04-16_09h20.29.214.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/493661_online_test_2026-03-26_17h34.07.857.csv
File /home/hugo/gitlab.pavlovia/online_test/data/coucou_online_test_2026-02-06_13h20.55.915.csv is older than cutoff date: 2026-03-25 00:00:00
Processing file /home/hugo/gitlab.pavlovia/online_test/data/828665_online_test_2026-03-26_17h25.43.703.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/410251_online_test_2026-04-16_16h17.08.740.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/457128_online_test_2026-04-16_15h16.37.142.csv
Processing file /home/hugo/gitlab.pavlovia/online_test/data/611499_online_test_2026-04-16_14h15.48.787.csv
135  were collected

In [3]:
df = pd.read_csv('data/preload_data.csv')

In [4]:
df['judge_ID'].nunique()

135

In [5]:
df_analysis = df[df['done']].copy()
df_analysis = df_analysis.drop('Unnamed: 0', axis=1 )
df_analysis['clip_uid'] = df_analysis['scene_id'].astype(str) + "_" + df_analysis['player'].astype(str) + "_" + df_analysis['clip'].astype(str)

In [6]:
for scene in df_analysis['scene_id'].unique():
    df_f = df_analysis[df_analysis['scene_id']==scene]
    print('For scene ',scene,' they are', df_f['participant'].nunique(),'judge')
df_analysis['scene_id'].value_counts()

For scene  w3l1s1  they are 21 judge
For scene  w2l3s8  they are 26 judge
For scene  w4l1s7  they are 37 judge
For scene  w5l2s2  they are 29 judge
For scene  w7l3s4  they are 22 judge

scene_id
w5l2s2    11136
w4l1s7    10952
w7l3s4     8800
w3l1s1     8400
w2l3s8     8112
Name: count, dtype: int64

In [7]:
df_analysis.head()

,participant,judge_ID,scene_id,player,question,clip,answer,visualisation_time,clip_path,video_duration,done,clip_uid
0,879453,666851e8b2c5dd35c6aaf99d,w3l1s1,ppo,Q_exH,0,True,29.2107,sourcedata/ppo_mario_ep-20/sub-01/ses-002/beh/...,3.166667,True,w3l1s1_ppo_0
1,879453,666851e8b2c5dd35c6aaf99d,w3l1s1,ppo,Q_exH,1,False,25.1595,sourcedata/ppo_mario_ep-20/sub-01/ses-002/beh/...,2.416667,True,w3l1s1_ppo_1
2,879453,666851e8b2c5dd35c6aaf99d,w3l1s1,ppo,Q_exH,2,False,10.2153,sourcedata/ppo_mario_ep-20/sub-01/ses-002/beh/...,2.416667,True,w3l1s1_ppo_2
3,879453,666851e8b2c5dd35c6aaf99d,w3l1s1,ppo,Q_exH,3,True,13.9311,sourcedata/ppo_mario_ep-20/sub-01/ses-002/beh/...,2.400000,True,w3l1s1_ppo_3
4,879453,666851e8b2c5dd35c6aaf99d,w3l1s1,ppo,Q_exH,4,False,12.5782,sourcedata/ppo_mario_ep-20/sub-01/ses-002/beh/...,2.416667,True,w3l1s1_ppo_4

In [46]:
# --- 3. Agreement Metrics Outliers (< Mean - 1*SD) ---
metric_outliers = set()
judge_metrics = {j: {'percent': [], 'kappa': [], 'dice': []} for j in df_analysis['judge_ID'].unique()}
ref = pd.read_csv('/home/hugo/gitlab.pavlovia/online_test/sourcedata/consensus_reference.csv')
for (scene, player), group in df_analysis.groupby(['scene_id', 'player']):
        # Pivot answers: Index=[question, clip], Columns=judge_ID

        ref_subset = ref[
        (ref['scene_id'] == scene) &
        (ref['player'] == player)
        ]
        pivoted = group.pivot_table(index=['question', 'clip'], columns='judge_ID', values='answer')
        consensus = ref_subset.pivot_table(index=['question', 'clip'], values='answer').iloc[:, 0]
        #print(pivoted)
        #print(consensus)
        for judge in pivoted.columns:
            judge_ans = pivoted[judge]
            aligned = pd.concat([judge_ans, consensus], axis=1, keys=['judge', 'consensus']).dropna()
            v1 = aligned['judge'].astype(int)
            v2 = aligned['consensus'].astype(int)
            judge_metrics[judge]['percent'].append((v1 == v2).mean())
            try:
                k = cohen_kappa_score(v1, v2)
                if np.isnan(k): print('Kappa non dfini pour ',judge)
                judge_metrics[judge]['kappa'].append(k)
            except Exception as e:
                print(f"Kappa error for {judge}, scene {scene}: {e}")
            judge_metrics[judge]['dice'].append(calculate_dice(v1, v2))
# Average metrics per judge
final_judge_metrics = []
for judge, measurements in judge_metrics.items():
        row = {'judge_ID': judge}
        for m in ['percent', 'kappa', 'dice']:
            row[m] = np.mean(measurements[m]) if measurements[m] else np.nan
        final_judge_metrics.append(row)
        
df_metrics = pd.DataFrame(final_judge_metrics)#.set_index('judge_ID')
    
outliers = df_metrics[df_metrics['kappa'] < 0.15]['judge_ID'].tolist()
metric_outliers.update(outliers)
        
#bad_boys = metric_outliers & set(time_outliers.keys())
#outliers_message = outliers_message+[f"{judge} saw less than 80% of video DURATION for {time_outliers[judge]} AND had extrem AGREEMENT measure: {df_metrics.loc[judge, :].to_list()} (percent, kappa, dice)\n" for judge in bad_boys]

print(len(metric_outliers))
metric_outliers

34

{'5e0b3d5dbf3d4e3868abc3ea',
 '5ecc0815f7f5db7c9c661508',
 '5fc6b25adb97a63895d5435f',
 '60551c921afebad605bfd329',
 '60a34e69c627c02da05a4619',
 '611f4665b4d9519095682405',
 '613a6a8a5d67441e6004f50c',
 '6154776b07de67ce15599bd5',
 '615cac6aa7e0f698abb5442c',
 '66156e2820c794a9a34aad79',
 '666b0b42bb6fa2822fa27a32',
 '66ce678bbaaf120fe160a530',
 '673caf90069aa7e3820136cc',
 '67d012f35c929bac3118c6f5',
 '695c0c263b49e67395e42b71',
 '695f9c1b1257661028e09d73',
 '697c89aa6ef612fb57786818',
 '697cae6e93b79bcf6b314046',
 '69807483ab18b3312485a744',
 '6980a4f0faef0e53cdfb97a7',
 '698165f74d737ae8dbb46f7a',
 '698255fa4fcb0cc777631bc2',
 '698345206d65b526d5a59d68',
 '6984783e42cc617bd5d288fd',
 '698b761436a8f2fae4910fb1',
 '698b8d194b513223c9e3d06b',
 '698e02489a2ba0896ae583ca',
 '699a44b0eec33f0efb8996b1',
 '699de824d503ec32677f0e8a',
 '69b2dfa3578726afc01d223c',
 '69bb0909fe9a6471ecdfb3b2',
 '69c62fc9b1c8ff76d5ced051',
 '69d648d33057d63617173b85',
 '69d8a676a584c578712ba8b3'}

In [45]:
px.scatter(df_metrics, x='kappa', y='dice', color='judge_ID')

In [47]:
px.histogram(df_metrics, x='kappa', nbins=40)

In [50]:
time_outliers = set()
print(df_analysis.keys())
df_bad_clips = []
for judge in df_analysis['judge_ID'].unique():

    judge_df = df_analysis[df_analysis['judge_ID'] == judge]
    participant = judge_df['participant'].iloc[0]
        
    # Group by clip to get max vis time for this judge/clip
    judge_clip_stats = judge_df.groupby('clip_uid').agg({
    'visualisation_time': 'max',
    'video_duration': 'first'
    })

    bad_clips = []
    is_time_outlier = False
    for clip_uid, row in judge_clip_stats.iterrows():

        max_vis = row['visualisation_time']
        duration = row['video_duration']
        if pd.notnull(duration) and duration > 0:
            if max_vis < 0.8 * duration:
                    is_time_outlier = True
                    #print('For ', clip_uid, ' visualistion was not sufficient, with: ',duration, 'and max_viz at: ', max_vis)
    
        if is_time_outlier:
            #print(judge, '/',participant ,'is a outilier')
            df_bad_clips.append({
             'judge':judge,
             'participant':participant,
             'bad_clips': clip_uid
            })
        
    if is_time_outlier:
        time_outliers.add(judge)

df_bad_clips = pd.DataFrame(df_bad_clips)
print(df_bad_clips.shape)
#print('Bad boys: ',df_bad_clips['judge'].unique())
print('Nb of Bad boys:',df_bad_clips['judge'].nunique())
print('Nb of bad clips per bad boys: ', df_bad_clips['judge'].value_counts())
#print('Details: ', df_bad_clips['bad_clips'].value_counts())

df_bad_clips.head()

Index(['participant', 'judge_ID', 'scene_id', 'player', 'question', 'clip',
       'answer', 'visualisation_time', 'clip_path', 'video_duration', 'done',
       'clip_uid'],
      dtype='str')
(4034, 3)
Nb of Bad boys: 68
Nb of bad clips per bad boys:  judge
699d5a17143facd69eabf01d    93
695c0c263b49e67395e42b71    88
6984783e42cc617bd5d288fd    87
611f4665b4d9519095682405    87
6977bd8c4a66002ceaa54c1d    86
                            ..
60f1019654f6a6ba79823b19    24
6983546a03db57593e6ddaa9    17
67e1b73ed47c36b4acd92c55    17
69d648d33057d63617173b85     8
66ce678bbaaf120fe160a530     2
Name: count, Length: 68, dtype: int64

                      judge participant      bad_clips
0  68e3cfc22688ddaae48dc6c3      951008  w2l3s8_ppo_27
1  68e3cfc22688ddaae48dc6c3      951008  w2l3s8_ppo_28
2  68e3cfc22688ddaae48dc6c3      951008  w2l3s8_ppo_29
3  68e3cfc22688ddaae48dc6c3      951008   w2l3s8_ppo_3
4  68e3cfc22688ddaae48dc6c3      951008  w2l3s8_ppo_30

In [51]:
import plotly.express as px
px.histogram(df_bad_clips, x='bad_clips')

In [11]:
df_analysis.head()
df_analysis = df_analysis[df_analysis['scene_id']=='w4l1s7']
df_analysis = df_analysis[df_analysis['judge_ID']!='66a9d46ff5d39bbede9f2e92']
print(df_analysis['judge_ID'].nunique())

34

In [14]:
bad_boys = set(df_bad_clips['judge'].unique()) & set(metric_outliers)
bad_boys

{'5e7a0cc0c4ee0904d8d5f154',
 '6151cac776c9ba6b61b3351b',
 '6266aba991affe86ae58ce07',
 '655fe1e57ede6fae3cc26bf0',
 '698074881d252d37dd9bc4d2',
 '69835875bb8198dfcaf4deaa',
 '6997dd1f7023de25b5608079'}

In [15]:
print(df_metrics['judge_ID'].nunique())
df_metrics.head()

34

                   judge_ID   percent     kappa      dice
0  6914df8bbecd11a94b6ddb2f  0.689189  0.185918  0.395010
1  6984ac6d0a79fdefd7b87a09  0.807432  0.527710  0.658491
2  5ffcd83b5991d41cc6d5cb40  0.746622  0.474396  0.648003
3  698074881d252d37dd9bc4d2  0.560811 -0.119194  0.180359
4  5dbc09abbc03131b83aeeacd  0.658784  0.111448  0.341088

In [16]:
px.histogram(df_metrics, x='kappa', nbins=30)

In [17]:
px.scatter(df_metrics, x='kappa', y='dice', color='judge_ID')

In [46]:
df_filtered = df_analysis[~df_analysis['judge_ID'].isin(bad_boys)]
df_filtered['judge_ID'].nunique()
df_filtered_hm = df_filtered[df_filtered['player']=='ppo']
df_hm = df_filtered_hm.groupby(['clip', 'question'], as_index=False).agg({
    'answer': 'mean',
    })
df_hm

     clip question    answer
0       0    Q_eff  0.518519
1       0    Q_exH  0.296296
2       0    Q_exL  0.555556
3       0    Q_ext  0.370370
4       1    Q_eff  0.407407
..    ...      ...       ...
143    35    Q_ext  0.814815
144    36    Q_eff  0.666667
145    36    Q_exH  0.074074
146    36    Q_exL  0.037037
147    36    Q_ext  0.777778

[148 rows x 3 columns]

In [50]:
import plotly.express as px
data = df_hm[(df_hm['question']=='Q_exL') | (df_hm['question']=='Q_ext')]
data = data[df_hm['clip']<27]
fig = px.bar(
    data,
    x="clip",
    y="answer",
    color="answer",                 # 👈 continuous color mapping
    color_continuous_scale="Viridis",
    facet_row="question",           # 👈 like your subplots
)

fig.update_layout(
    title="Frequency of responses over each clip",
    height=100 * df['question'].nunique()
)

fig.show()

/tmp/ipykernel_118616/1224353372.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data = data[df_hm['clip']<27]

In [33]:
from my_analysis.metrics import calculate_metrics_panel_sweep
metrics = ['dice', 'percent', 'kappa']
# Panel sizes to test
panel_sizes = [1, 3, 5, 9, 13, 15]
results = calculate_metrics_panel_sweep(df_filtered, metrics, panel_sizes)

Processing Scene: w4l1s7, Player: ppo
  Testing panel size: 1
  Testing panel size: 3

/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)

  Testing panel size: 5

/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)

  Testing panel size: 9

/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)

  Skipping panel size 13: not enough judges (23)
  Skipping panel size 15: not enough judges (23)
Processing Scene: w4l1s7, Player: sub-03
  Testing panel size: 1
  Testing panel size: 3

/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/hugo/gitlab.pavlovia/online_test/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:991: RuntimeWarning: invalid value encountered in scalar divide
  k = xp.sum(w_mat * confusion) / xp.sum(w_mat * expected)

  Testing panel size: 5
  Testing panel size: 9
  Skipping panel size 13: not enough judges (23)
  Skipping panel size 15: not enough judges (23)

In [35]:
from my_analysis.viz import (plot_panel_size_sweep, 
                                          plot_scene_agreement_summary, 
                                          plot_global_agreement_summary, 
                                          plot_correlation_matrix, 
                                          plot_mean_correlation_matrix)
output_dir = os.path.join(os.getcwd(), 'outputdata')
plots_output_path = os.path.join(output_dir, 'results')

plot_scene_agreement_summary(results, output_path=plots_output_path)
plot_correlation_matrix(df_filtered, output_path=plots_output_path)

{'w4l1s7_corr': <Figure size 1000x800 with 2 Axes>}